/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PresaleConfig = IDL.Record({
  'presaleEndTimestamp' : IDL.Int,
  'walletAddress' : IDL.Text,
  'softCapSol' : IDL.Float64,
  'tokenName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getConfig' : IDL.Func([], [PresaleConfig], ['query']),
  'getPresaleEndTimestamp' : IDL.Func([], [IDL.Int], ['query']),
  'getSoftCapSol' : IDL.Func([], [IDL.Float64], ['query']),
  'getTokenName' : IDL.Func([], [IDL.Text], ['query']),
  'getWalletAddress' : IDL.Func([], [IDL.Text], ['query']),
  'setConfig' : IDL.Func([IDL.Text, IDL.Int, IDL.Float64, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PresaleConfig = IDL.Record({
    'presaleEndTimestamp' : IDL.Int,
    'walletAddress' : IDL.Text,
    'softCapSol' : IDL.Float64,
    'tokenName' : IDL.Text,
  });
  
  return IDL.Service({
    'getConfig' : IDL.Func([], [PresaleConfig], ['query']),
    'getPresaleEndTimestamp' : IDL.Func([], [IDL.Int], ['query']),
    'getSoftCapSol' : IDL.Func([], [IDL.Float64], ['query']),
    'getTokenName' : IDL.Func([], [IDL.Text], ['query']),
    'getWalletAddress' : IDL.Func([], [IDL.Text], ['query']),
    'setConfig' : IDL.Func([IDL.Text, IDL.Int, IDL.Float64, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };